# Database settings
database:
  type: "sqlite" # sqlite or mysql

# MySQL settings (used only if database.type is mysql)
mysql:
  username: "root"
  password: ""
  databaseName: "advancement_ranking"
  host: "127.0.0.1"
  port: 3306

# View settings
disable_top3: false
